#!/usr/bin/env python3

def temp_converter(current_type, current_tempt):
    if (current_type == "C"):
        converted_tempt = 32 + current_tempt*(9/5)
        return converted_tempt
    elif (current_type == "F"):
        converted_tempt = (current_tempt -32) * (5/9)
        return converted_tempt
    else:
        converted_tempt = "The current type you use is not accepted.  Pluse use C or F for current type and a number for current temperature"
        return converted_tempt
        
        
converted_tempt = tempt_converter(current_type, current_tempt)
print(converted_tempt)
